---
apiVersion: extensions/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name: front-end
  namespace: sock-shop
spec:
  scaleRef:
    kind: Deployment
    name: front-end
    subresource: scale
  minReplicas: 2
  maxReplicas: 5
  cpuUtilization:
    targetPercentage: 10
